site: Index Jekyll Theme

target: https://index.jekyllthemes.io
baseurl: 

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "images/small"
    values:
      image: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

#plugins:
  #- jekyll-image-size

collections:
  lehrveranstaltungen:
    output: false
  feed:
    output: true
  misc:
    output: true
  thoughts:
    output: true
  checkItOut:
    output: false
  books:
    output: true
  links:
    output: true
  diary:
    output: false
  vita:
    output: false
    
## plugins:
#  - jekyll-paginate
#  - jekyll-sitemap

  