basic_settings:
  site_title: Christian Noss
  site_tagline: prof @th_koeln // founder @klickmeister // \#longboarding \#snowboarding \#mtb \#music \#drums
  favicon_image: /images/favicon.ico
  description: Bei Fragen, coolen Projektideen oder Freizeitaktivitäten bitte melden :)
  featured_image: https://christiannoss.de/images/cab-sw-normal-1x1.jpg


advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""