local_backend: true

backend:
  name: git-gateway
  repo: cnoss/home
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'images'

collections:
  - name: 'feed'
    label: 'Schöne Ergebnisse'
    folder: '_feed/'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Autor:in', name: 'author', widget: 'string' }
      - { label: 'Term', name: 'term', widget: 'string' }
      - { label: 'URL', name: 'target', widget: 'string' }
      - { label: 'Context', name: 'context', widget: 'hidden', default: 'gg' }
      - { label: 'Startseite', name: 'home', widget: 'boolean', default: true}
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
  - name: 'check-it-out'
    label: 'Mal austesten?'
    folder: '_checkItOut/'
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {label: 'Content', name: 'body', widget: 'text'}
  - name: 'diary'
    label: 'Diary'
    folder: '_diary/'
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {label: 'Content', name: 'body', widget: 'text'}
  - name: 'vita'
    label: 'Vita'
    folder: '_vita/'
    slug: "{{fields.year}}-{{fields.month}}-{{filename}}"
    create: true
    search: true
    sortable_fields: ['year', 'title']
    view_groups:
      - label: Type
        field: type
      - label: Year
        field: year

    fields:
      - { label: 'Filename', name: 'filename', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {label: 'Headline', name: 'headline', widget: 'string', required: true}
      - {label: 'Content', name: 'body', widget: 'text', required: false}
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["vita", "award", "teaching", "university-related-commitment"]
      - {label: 'Since', name: 'since', widget: 'boolean', default: false, required: false}
      - { label: 'Year', name: 'year', widget: 'number' }
      - { label: 'Month', name: 'month', widget: 'number', required: false }
      - { label: 'Day', name: 'day', widget: 'number', required: false }
      - { label: 'Year until', name: 'yearUntil', widget: 'number', required: false }
      - { label: 'Month until', name: 'monthUntil', widget: 'number', required: false }
      - { label: 'Day until', name: 'dayUntil', widget: 'number', required: false }
      - { label: 'Additional Content', name: 'additionalContent', widget: 'text', required: false }
      - label: "Downloads"
        name: "downloads"
        widget: "file"
        required: false
        default: "/uploads/"
        media_library:
          config:
            multiple: true