local_backend: true

backend:
 name: git-gateway
 branch: main # Branch to update (optional; defaults to master)

media_folder: 'images'

collections:
  - name: 'feed'
    label: 'Schöne Ergebnisse'
    folder: '_feed/'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Autor:in', name: 'author', widget: 'string' }
      - { label: 'Term', name: 'term', widget: 'string' }
      - { label: 'URL', name: 'target', widget: 'string' }
      - { label: 'Context', name: 'context', widget: 'hidden', default: 'gg' }
      - { label: 'Startseite', name: 'home', widget: 'boolean', default: true}
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
  - name: 'check-it-out'
    label: 'Mal austesten?'
    folder: '_checkItOut/'
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {label: 'Content', name: 'body', widget: 'text'}